title: Trevor Langley
email: tlangley@mit.edu
description: Mechanical engineering student at MIT.
baseurl: ""
url: "https://langley.github.io"

author: Trevor Langley

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  albums:
    output: true
    permalink: /music/:name/

permalink: /blog/:year/:month/:day/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
